### ISSUE TITLE
Alarm Decoder Disconnect - Related to Home Assistant?

### ISSUE THREAD

**Issue by SP410** [nutechsoftware/alarmdecoder#25]
Hello Alarm Decoder team, while using Home Assistant, the following error was reported from Alarm Decoder.  I am very hopeful you are able to help, I quite enjoy using alarm decoder with my home automation system.  

For more information, see: 
https://github.com/home-assistant/home-assistant/issues/14352

Error during setup of component alarmdecoder
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/alarmdecoder.py", line 166, in setup
    AlarmDecoder(USBDevice.find())
  File "/usr/lib/python3.6/site-packages/alarmdecoder/devices/usb_device.py", line 109, in find
    raise ImportError('The USBDevice class has been disabled due to missing requirement: pyftdi or pyusb.')
ImportError: The USBDevice class has been disabled due to missing requirement: pyftdi or pyusb.

**Comment by weevis** [comment]
Install the correct pyftdi version or switch to using a serial device type

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

**Comment by SP410** [comment]
When using serial device type, I experience random disconnects in home assistant (this is how I currently use Alarm Decoder).  The home assistant devs advise that nutech is importing dependencies in-correctly.  Any advice?

**Comment by weevis** [comment]
Do you experience these disconnects outside of home assistant?  Would love
to debug an actual issue with the AlarmDecoder library if there is one.

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

**Comment by SP410** [comment]
I switched to Ser2Sock via docker.  There is no indication of an error; the AUI messages just stop working.  

After restarting Ser2Sock (no changes to USB), I receive the following: 

[✔] Using config file: /etc/ser2sock.conf
[✔] Serial 2 Socket Relay version V1.5.5 starting
[✔] Listening socket created on port 8100
[✔] Start wait loop using ser2sock communication mode
[✔] Opened com port at /dev/ttyUSB0
[✔] Setting speed 115200
[✔] Set speed successful
[✔] Socket connected slot 2
[‼] Closing socket fd slot 2 errno: 0 'No error information'
[✔] Socket connected slot 2

Is there a way to enable more detailed logging?  Would love to find the issue.

**Comment by weevis** [comment]
What's your device configuration?  To see AUI I believe your configbits
need to be at least FF05

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

**Comment by WilsonBradley** [comment]
Hi,

Hoping you could help me figure what is going on. For some reason my alarm
system is stuck at [Please Wait Loading...]
I didn't do any updates, not sure Im getting a lot of python script errors.

​2018-06-27 13:33:37,840 INFO: AlarmDecoder Webapp booting up -
v0.8.1-9-g0664184 [in /opt/alarmdecoder-webapp/ad2web/decoder.py:222]
2018-06-27 13:33:38,170 ERROR: Error [in
/opt/alarmdecoder-webapp/ad2web/app.py:175]
Traceback (most recent call last):
File "/opt/alarmdecoder-webapp/ad2web/app.py", line 168, in init_app
app.decoder.init()
File "/opt/alarmdecoder-webapp/ad2web/decoder.py", line 240, in init
self._notifier_system = NotificationSystem()
File "/opt/alarmdecoder-webapp/ad2web/notifications/types.py", line 88, in
__init__
self._init_notifiers()
File "/opt/alarmdecoder-webapp/ad2web/notifications/types.py", line 214, in
_init_notifiers
self._notifiers[n.id] = TYPE_MAP[n.type](n)
File "/opt/alarmdecoder-webapp/ad2web/notifications/types.py", line 927, in
__init__
self.auth_username = self.auth_username.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2018-06-27 14:55:47,422 ERROR: Error sending keypress to device [in
/opt/alarmdecoder-webapp/ad2web/decoder.py:854]
Traceback (most recent call last):
File "/opt/alarmdecoder-webapp/ad2web/decoder.py", line 851, in on_keypress
self._alarmdecoder.device.send(key)
AttributeError: 'NoneType' object has no attribute 'send'
2018-06-27 14:55:48,343 ERROR: Error sending keypress to device [in
/opt/alarmdecoder-webapp/ad2web/decoder.py:854]
Traceback (most recent call last):
File "/opt/alarmdecoder-webapp/ad2web/decoder.py", line 851, in on_keypress
self._alarmdecoder.device.send(key)
AttributeError: 'NoneType' object has no attribute 'send'
2018-06-27 14:55:49,264 ERROR: Error sending keypress to device [in
/opt/alarmdecoder-webapp/ad2web/decoder.py:854]
Traceback (most recent call last):
File "/opt/alarmdecoder-webapp/ad2web/decoder.py", line 851, in on_keypress
self._alarmdecoder.device.send(key)
AttributeError: 'NoneType' object has no attribute 'send'
2018-06-27 14:55:50,083 ERROR: Error sending keypress to device [in
/opt/alarmdecoder-webapp/ad2web/decoder.py:854]
Traceback (most recent call last):
File "/opt/alarmdecoder-webapp/ad2web/decoder.py", line 851, in on_keypress
self._alarmdecoder.device.send(key)
AttributeError: 'NoneType' object has no attribute 'send'
2018-06-27 14:55:55,348 ERROR: Error sending keypress to device [in
/opt/alarmdecoder-webapp/ad2web/decoder.py:854]
Traceback (most recent call last):
File "/opt/alarmdecoder-webapp/ad2web/decoder.py", line 851, in on_keypress
self._alarmdecoder.device.send(key)
AttributeError: 'NoneType' object has no attribute 'send'
2018-06-27 14:56:07,669 ERROR: Error sending keypress to device [in
/opt/alarmdecoder-webapp/ad2web/decoder.py:854]
Traceback (most recent call last):
File "/opt/alarmdecoder-webapp/ad2web/decoder.py", line 851, in on_keypress
self._alarmdecoder.device.send(key)
AttributeError: 'NoneType' object has no attribute 'send'
2018-06-27 15:09:26,151 INFO: AlarmDecoder Webapp booting up -
v0.8.1-5-gb072411 [in /opt/alarmdecoder-webapp/ad2web/decoder.py:222]
2018-06-27 15:09:26,481 ERROR: Error [in
/opt/alarmdecoder-webapp/ad2web/app.py:175]
Traceback (most recent call last):
File "/opt/alarmdecoder-webapp/ad2web/app.py", line 168, in init_app
app.decoder.init()
File "/opt/alarmdecoder-webapp/ad2web/decoder.py", line 240, in init
self._notifier_system = NotificationSystem()
File "/opt/alarmdecoder-webapp/ad2web/notifications/types.py", line 88, in
__init__
self._init_notifiers()
File "/opt/alarmdecoder-webapp/ad2web/notifications/types.py", line 214, in
_init_notifiers
self._notifiers[n.id] = TYPE_MAP[n.type](n)
File "/opt/alarmdecoder-webapp/ad2web/notifications/types.py", line 927, in
__init__
self.auth_username = self.auth_username.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
​



Sincerely,

Wilson Bradley
Wilsonb@pobox.com

**Comment by WilsonBradley** [comment]
The Web server was working in the past

Using the Windows App it communicates.





Sincerely,

Wilson Bradley
Wilsonb@pobox.com

**Comment by nwikner** [comment]
I am not an appropriate recipient for this email.  I am a customer, not a member of tech support.  I have no knowledge that can help you, nor can I interpret the code that you included.  The original email says “Cc: Subscribed”  perhaps you shouldn’t send it to everyone who is subscribed to the thread.
Norman Wikner
wikner.norman@gmail.com



On Jun 27, 2018, at 3:00 PM, Wilson K Bradley <notifications@github.com> wrote:

The Web server was working in the past

Using the Windows App it communicates.





Sincerely,

Wilson Bradley
Wilsonb@pobox.com

**Comment by WilsonBradley** [comment]
Actually after the Windows app(latest) initialized it shows the screenshot
"Entering Running Mode , Waiting first message" however it had buffer
errors after a few min.




Here are my current seetings for DSC Alarm unit.




Sincerely,

Wilson Bradley
Wilsonb@pobox.com

**Comment by SP410** [comment]
For me issue was resolved by replacing the micro-usb cable.
