### ISSUE TITLE
Parsing error of older firmware 2.2a.8.6 causes exception.

### ISSUE THREAD

**Issue by f34rdotcom** [nutechsoftware/alarmdecoder#39]
Old 2.2a.8.6 firmware causes an exception.

[2019-09-03 15:47:58,463] INFO in decoder: AlarmDecoder device was opened.
[2019-09-03 15:48:01,483] INFO in decoder: AlarmDecoder device was closed.
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/alarmdecoder/alarmdecoder/devices/base_device.py", line 148,
in run
    self._device.read_line(timeout=self.READ_TIMEOUT)
  File "/opt/alarmdecoder/alarmdecoder/devices/socket_device.py", line 356,
in read_line
    self.on_read(data=ret)
  File "/opt/alarmdecoder/alarmdecoder/event/event.py", line 84, in fire
    func(self.obj, *args, **kwargs)
  File "/opt/alarmdecoder/alarmdecoder/decoder.py", line 1041, in _on_read
    self._handle_message(data)
  File "/opt/alarmdecoder/alarmdecoder/decoder.py", line 439, in
_handle_message
    msg = self._handle_keypad_message(data)
  File "/opt/alarmdecoder/alarmdecoder/decoder.py", line 477, in
_handle_keypad_message
    msg = Message(data)
  File "/opt/alarmdecoder/alarmdecoder/messages/panel_message.py", line 85,
in __init__
    self._parse_message(data)
  File "/opt/alarmdecoder/alarmdecoder/messages/panel_message.py", line
121, in _parse_message
    self.system_fault = int(self.bitfield[17], 16)
ValueError: invalid literal for int() with base 16: '-'

**Comment by bobbanks** [comment]
Hi @f34rdotcom.  Is there a resolution or work around for this?

**Comment by bobbanks** [comment]
I ended up resolving by upgrading to v2.2a.8.8

**Comment by f34rdotcom** [comment]
I suggest loading 2.2a.8.9b-306. 
This has been around a long time and fixes a few small bugs in 8.8 related to RFX messages and ... something else. I think SE panel issue.

Best
 SM

**Comment by jmgurney** [comment]
I'd like to see this fixed so that it can handle both firmware versions.  I've had to pin the older working version, but of course that change happened before the unlocking of pyserial, so I'm going to have to fork this repo to deal with that.
